include:
  - https://gitlab.com/GreyRook/cde/gitlab-ci-templates/raw/eea13b881d15abb97e2e1aac1d67f6f36fecf785/gitlab-ci-base.yml


image: greyrook/cde-dev-js:8e3a9103160e390efcd135faa0a0122aed7088c7


prettier:
  stage: test
  script:
    - yarn run lint-prettier


eslint:
  stage: test
  script:
    - yarn run lint
